FROM  amitkma/python-ffmpeg:3.12-slim
WORKDIR /encode
RUN pip install --no-cache-dir requests
RUN pip install --no-cache-dir boto3
RUN pip install "fastapi[standard]"
RUN pip install uvicorn
COPY ./streaming_nodes/s3_handler.py s3_handler.py
COPY ./streaming_nodes/Streaming_worker.py  Streaming_worker.py
COPY ./streaming_nodes/unzip_hls.py  unzip_hls.py
ENV PYTHONUNBUFFERED=1


ENTRYPOINT ["uvicorn", "Streaming_worker:servelet", "--host", "0.0.0.0", "--port", "8000"]
