services:
  go-stream-node:
    build:
      context: ..
      dockerfile: ../Docker/GO_NODE_DOCKER_FILES/DockerFile.gonode
    container_name: go_stream_node
    image: go-node-image
    ports:
      - "3002:3002"
    environment:
      END_POINT: "host.docker.internal:9000" #has to be changed on a prod, to the acutll ip adress of the s3 server
      ACCESS_kEY: "ktadmin"
      SECRET_ACCESS_KEY: "12345678"
      SSL_USE: "false"
    volumes:
      - go_node_store:/stream

  nginx:
    image: nginx:alpine
    container_name: streaming_node_proxy
    ports:
      - "4001:4001" #for  local dev i have made this to be a different port number than 80, will be 80 on prod
    depends_on:
      - go-stream-node
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  go_node_store:
