
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;


    gzip on;
    gzip_min_length 1000;
    gzip_types text/plain application/json text/css application/javascript;

    server {
        listen 4001;
        server_name _;


        location /stream/ {
            proxy_pass http://go-stream-node:3002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;}


            location = /auth{
                internal;
            proxy_pass http://host.docker.internal:80/api/v1/player/auth/vid;
            proxy_pass_request_body off;
            proxy_pass_header Authorization;
            proxy_set_header Content-Length "";
            proxy_set_header request_uri $request_uri;
            proxy_set_header current-frame $http_current_frame; # for incoming headers

            }


            location /vid/get/ {
            if ($request_method = OPTIONS) {
                add_header Access-Control-Allow-Origin  $http_origin always;
                add_header Access-Control-Allow-Methods "GET, OPTIONS"     always;
                add_header Access-Control-Allow-Headers "Authorization, Cache-Control, Pragma, Current-Frame" always;
                add_header Access-Control-Max-Age       86400              always;
                return 204;
            }

                auth_request /auth;
                alias /vid_store/unzipped/;

                add_header Access-Control-Allow-Origin  $http_origin always;
                add_header Access-Control-Allow-Headers "Authorization, Cache-Control, Pragma, Current-Frame" always;

            }
}
}
